
CONFIG_ARCH_V831=y

CONFIG_LIBMAIX_ENABLED=n
CONFIG_LVGL_ENABLE=n
CONFIG_LIBJPEG_ENABLE=n
CONFIG_CJSON_ENABLE=n
CONFIG_ZBAR_ENABLE=n
CONFIG_SQLITE3_ENABLE=n
CONFIG_APRILTAG_ENABLE=n
CONFIG_COMPONENT_3RD_PARTY_ENABLE=y
CONFIG_COMPONENT_IMAGE_ENABLE=n

CONFIG_TOOLCHAIN_PATH="/opt/v83x_linux_x86_python3.8_toolchain/toolchain-sunxi-musl/toolchain/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-openwrt-linux-muslgnueabi-"
